### ISSUE TITLE
RecursionError in header_login template

### ISSUE THREAD

**Issue by mirekys** [inveniosoftware/invenio-administration#180] opened 2023-08-24 10:25 UTC
Package version (if known): 1.0.6

## Describe the bug

When `invenio_theme/header_login.html` from this package gets registered before the same template provided by `invenio-theme` package, it recursively re-extends itself until the:
```
RecursionError: maximum recursion depth exceeded in comparison
```
error is reached.

## Steps to Reproduce

1. Install `invenio-theme==1.4.8`
2. Install `invenio-administration==1.0.6`
3. Include `{%- include config.THEME_HEADER_LOGIN_TEMPLATE %}` somewhere in your site (e.g. `header.html` template)
4. Sit back and wait until the recursion explodes with:

```
File "../mysite/...templates.../header.html", line 123, in block 'navbar_right'
{%- include config.THEME_HEADER_LOGIN_TEMPLATE %}
File "/invenio/venv/lib/python3.10/site-packages/invenio_administration/templates/semantic-ui/invenio_theme/header_login.html", line 10, in top-level template code
{%- extends "invenio_theme/header_login.html" %}
File "/invenio/venv/lib/python3.10/site-packages/invenio_administration/templates/semantic-ui/invenio_theme/header_login.html", line 10, in top-level template code
{%- extends "invenio_theme/header_login.html" %}`
...& so on
```

## Expected behavior

It should always extend the `invenio_theme/header_login.html` template,
but only the one provided by `invenio-theme`, in which there are no more includes & extends.

## Additional context

Default LOGIN_TEMPLATE config value is used:
```
THEME_HEADER_LOGIN_TEMPLATE = "invenio_theme/header_login.html"
```

**Comment by utnapischtim** [comment] 2024-07-23 12:38
I couldn't reproduce this bug.

What i have tried:
- added `{%- include config.THEME_HEADER_LOGIN_TEMPLATE %}` to `invenio_app_rdm/header.html`.

Results:
- the user menu was there twice (expected)
- but NO errors

closing it

**Closed by utnapischtim** 2024-07-23 12:38 UTC
Labels: bug
